version: "3.9"
services:
  server:
    build: ./server
    ports:
    - "5000:5000"
    volumes:
    - ./server:/app
    environment:
      FLASK_DEBUG: 1
  frontend:
    build: ./frontend
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/user/src/app